number1=int(input("enter number:"))
number2=int(input("enter number:"))

print(number1+number2)
print(number1-number2)
print(number1*number2)
print(number1/number2)
print(number1//number2)
print(number1%number2)
print(number1**number2)
